stages:   
  - build-HotelService       # List of stages for jobs, and their order of execution
  - build-BookingService
  - test

build-BookingService:       # This job runs in the build stage, which runs first.
  stage: build-BookingService
  script:
     - "cd ./back-end/BookingService"
     - "dotnet build"

build-HotelService:       # This job runs in the build stage, which runs first.
  stage: build-HotelService
  script:
     - "cd ./back-end/HotelService"
     - "dotnet build"

