stages:   
  - HotelService
  - BookingService

build-BookingService:  
  stage: BookingService
  script:
     - "cd ./back-end/BookingService"
     - "dotnet build /nodereuse:false"

test-BookingService:   
  stage: BookingService
  script:
     - "cd ./back-end/BookingService"
     - "dotnet test /nodereuse:false"

deploy-BookingService:
  stage: BookingService
  script:
     - "cd ./back-end/BookingService"
     - "docker build -f ./BookingService/Dockerfile -t bforslund/semester-6-booking:$CI_JOB_ID ."
     - "docker login -u $docker_username -p $docker_password"
     - "docker push bforslund/semester-6-booking:$CI_JOB_ID"
     - "cd ../../kubernetes"
     - $commandArgument = ".spec.template.spec.containers[0].image = """"bforslund/semester-6-booking:$CI_JOB_ID"""""
     - yq -i "$commandArgument" bookingservice-deployment.yaml
     - git config --global user.email "${GITLAB_USER_EMAIL}"
     - git config --global user.name "${GITLAB_USER_NAME}"
     - git add bookingservice-deployment.yaml
     - git commit -m "Update kubernetes deployment to booking:$CI_JOB_ID"
     #- git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
     - git push # Pushes to the same branch as the trigger


# build-HotelService: 
#   stage: HotelService
#   script:
#      - "cd ./back-end/HotelService"
#      - "dotnet build /nodereuse:false"

# test-HotelService:   
#   stage: HotelService
#   script:
#      - "cd ./back-end/HotelService"
#      - "dotnet test /nodereuse:false"

deploy-HotelService:
  stage: HotelService
  script:
     - "cd ./back-end/HotelService"
    #  - "docker build -f ./HotelService/Dockerfile -t bforslund/semester-6-hotel:$CI_JOB_ID ."
    #  - "docker login -u $docker_username -p $docker_password"
    #  - "docker push bforslund/semester-6-hotel:$CI_JOB_ID"
     - "cd ../../kubernetes"
     - $commandArgument = ".spec.template.spec.containers[0].image = """"bforslund/semester-6-hotel:$CI_JOB_ID"""""
     - yq -i "$commandArgument" hotelservice-deployment.yaml 
     - git config --global user.email "${GITLAB_USER_EMAIL}"
     - git config --global user.name "${GITLAB_USER_NAME}
     - git add hotelservice-deployment.yaml
     - git commit -m "[ci skip] [skip ci] Update kubernetes deployment to hotel:$CI_JOB_ID"
     - git remote rm origin
     - git remote add origin https://git.fhict.nl/I431685/semester-6-project.git
     - git push


# hotel-sonarqube-check:
#   stage: HotelService
#   variables:
#     GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#   script: 
#       - "$Env:PATH+=';C:\\Users\\Bea\\.dotnet\\tools\\'"
#       - "cd ./back-end/HotelService"
#       - "dotnet sonarscanner begin /k:\"Semester-6-HotelService\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
#       - "dotnet build /nodereuse:false"
#       - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
#   only:
#     - main # or the name of your main branch

# booking-sonarqube-check:
#   stage: BookingService
#   variables:
#     GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#   script: 
#       - "$Env:PATH+=';C:\\Users\\Bea\\.dotnet\\tools\\'"
#       - "cd ./back-end/BookingService"
#       - "dotnet sonarscanner begin /k:\"Semester-6-BookingService\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
#       - "dotnet build /nodereuse:false"
#       - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
#   only:
#     - main # or the name of your main branch

