stages:   
  - HotelService
  - BookingService

build-BookingService:  
  stage: BookingService
  script:
     - "cd ./back-end/BookingService"
     - "dotnet build /nodereuse:false"

test-BookingService:   
  stage: BookingService
  script:
     - "cd ./back-end/BookingService"
     - "dotnet test /nodereuse:false"

deploy-BookingService:
  stage: BookingService
  script:
     - "cd ./back-end/BookingService"
     - "docker build -f ./BookingService/Dockerfile -t bookingservice:latest -t bforslund/bookingservice:latest ."
     - "docker login -u $docker_username -p $docker_password"
     - "docker push bforslund/semester-6-booking:latest"


build-HotelService: 
  stage: HotelService
  script:
     - "cd ./back-end/HotelService"
     - "dotnet build /nodereuse:false"

test-HotelService:   
  stage: HotelService
  script:
     - "cd ./back-end/HotelService"
     - "dotnet test /nodereuse:false"

deploy-HotelService:
  stage: HotelService
  script:
     - "cd ./back-end/HotelService"
     - "docker build -f ./HotelService/Dockerfile -t hotelservice:latest -t bforslund/hotelservice:dev ."
     - "docker login -u $docker_username -p $docker_password"
     - "docker push bforslund/semester-6-hotel:latest"

# hotel-sonarqube-check:
#   stage: HotelService
#   variables:
#     GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#   script: 
#       - "$Env:PATH+=';C:\\Users\\Bea\\.dotnet\\tools\\'"
#       - "cd ./back-end/HotelService"
#       - "dotnet sonarscanner begin /k:\"Semester-6-HotelService\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
#       - "dotnet build /nodereuse:false"
#       - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
#   only:
#     - main # or the name of your main branch

# booking-sonarqube-check:
#   stage: BookingService
#   variables:
#     GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#   script: 
#       - "$Env:PATH+=';C:\\Users\\Bea\\.dotnet\\tools\\'"
#       - "cd ./back-end/BookingService"
#       - "dotnet sonarscanner begin /k:\"Semester-6-BookingService\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
#       - "dotnet build /nodereuse:false"
#       - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
#   only:
#     - main # or the name of your main branch

