stages:   
  - build-HotelService
  - test-HotelService 
  - build-BookingService
  - test-BookingService

build-BookingService:  
  stage: build-BookingService
  script:
     - "cd ./back-end/BookingService"
     - "dotnet build"

test-BookingService:   
  stage: test-BookingService
  script:
     - "cd ./back-end/BookingService"
     - "dotnet test"

build-HotelService: 
  stage: build-HotelService
  script:
     - "cd ./back-end/HotelService"
     - "dotnet build"

test-HotelService:   
  stage: test-HotelService
  script:
     - "cd ./back-end/HotelService"
     - "dotnet test"

