apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingservice
  labels:
    app: bookingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingservice
  template:
    metadata:
      labels:
        app: bookingservice
    spec:
      revisionHistoryLimit: 0
      containers:
        - name: bookingservice
          image: bforslund/semester-6-booking:122738
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: RABBITMQ_HOSTNAME
              value: rabbitmq-client.default.svc.cluster.local
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
            limits:
              cpu: 200m
