apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingservice
  labels:
    app: bookingservice
spec:
  # revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: bookingservice
  template:
    metadata:
      labels:
        app: bookingservice
    spec:
      containers:
        - name: bookingservice
          image: bforslund/semester-6-booking:126104
          imagePullPolicy: Always
          # volumeMounts:

          #   - name: secrets-store01-inline

          #     mountPath: "/mnt/secrets-store"

          #     readOnly: true
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: RABBITMQ_HOSTNAME
              value: rabbitmq-client.default.svc.cluster.local
            - name: DbConnectionString
              value: Server=bookingdatabase.mysql.database.azure.com;UserID = adminbea;Password=Password1;Database=bookingdatabase;
              # valueFrom:
          #   secretKeyRef:

          #     name: bookingservice-secret

          #     key: booking-connectionString
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 350m
      # volumes:

#   - name: secrets-store01-inline

#     csi:

#       driver: secrets-store.csi.k8s.io

#       readOnly: true

#       volumeAttributes:

#         secretProviderClass: "azure-kvname-system-msi"
