apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelQueryService
  labels:
    app: hotelQueryService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotelQueryService
  template:
    metadata:
      labels:
        app: hotelQueryService
    spec:
      containers:
        - name: hotelQueryService
          image: bforslund/semester-6-hotelqueryservice:122720
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DbConnectionString
              value: Server=hoteldatabase.mysql.database.azure.com;UserID = adminbea;Password=Password1;Database=hoteldatabase;
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 200m
