apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotelservice
spec:
  rules:
  - host: hotel.bea.local 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hotelservice
            port:
              name: http
