apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelservice
  labels:
    app: hotelservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotelservice
  template:
    metadata:
      labels:
        app: hotelservice
    spec:
      containers:
        - name: hotelservice
          image: bforslund/semester-6-hotel:122711
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: RABBITMQ_HOSTNAME
              value: rabbitmq-client.default.svc.cluster.local
            - name: DbConnectionString
              value: Server=hoteldatabase.mysql.database.azure.com;UserID = adminbea;Password=Password1;Database=hoteldatabase;
            - name: AppConfiguration__AccessKey
              value: AKIAXR57OWGB5IKRZNHO
            - name: AppConfiguration__SecretKey
              value: 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
            - name: AppConfiguration__BucketName
              value: hotelpictures
            - name: JWT_token
              value: oeRaYY7Wo24sDqKSX
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 200m
