apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelservice
  labels:
    app: hotelservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotelservice
  template:
    metadata:
      labels:
        app: hotelservice
    spec:
      containers:
        - name: hotelservice
          image: bforslund/semester-6-hotel:121227
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: RABBITMQ_HOSTNAME
              value: rabbitmq-client.default.svc.cluster.local
            - name: ConnectionStrings__DefaultConnection
              value: Server=bookingdatabase.mysql.database.azure.com;UserID = adminbea;Password=Password1;Database=bookingdatabase;
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 200m
