apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hotelservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotelservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50