# # This is a SecretProviderClass example using system-assigned identity to access your key vault
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-kvname-system-msi
# spec:
#   provider: azure
#   secretObjects:                           
#     - secretName: hotelservice-secret                     # name of the Kubernetes secret object
#       type: Opaque  
#       data:
#       - key: connectionString                          
#         objectName: hotelDB--DefaultConnection                       
#       - key: aws3-accesskey-key                           
#         objectName: aws3-accesskey 
#       - key: aws3-secretkey-key                       
#         objectName: aws3-secretkey
#       - key: jwt_token
#         objectName: jwt-token
#       - key: redisConnection
#         objectName: redis-Connection  
#     - secretName: bookingservice-secret                     # name of the Kubernetes secret object
#       type: Opaque  
#       data:
#       - key: booking-connectionString                          
#         objectName: bookingDB--DefaultConnection                                     
#   parameters:
#     tenantId: c66b6765-b794-4a2b-84ed-845b341c086a        
#     usePodIdentity: "false"
#     useVMManagedIdentity: "true"    # Set to true for using managed identity
#     userAssignedIdentityID: "105b4b17-20fb-4164-9032-a922447f1897" 
#     keyvaultName: application-secrets
#     objects:  |
#       array:
#         - |
#           objectName: hotelDB--DefaultConnection
#           objectType: secret 
#         - |
#           objectName: bookingDB--DefaultConnection
#           objectType: secret        
#         - |
#           objectName: aws3-accesskey
#           objectType: secret 
#         - |
#           objectName: aws3-secretkey
#           objectType: secret   
#         - |
#           objectName: jwt-token
#           objectType: secret
#         - |
#           objectName: redis-Connection
#           objectType: secret      
       
